trigger:
  branches:
    include:
      - main

variables:
  sonarProjectKey: 'SonarQubeArun'
  sonarProjectName: 'SonarQubeArun'
  sonarHostUrl: 'http://98.70.57.201:9000'
  sonarToken: 'sqp_0a4b770d57dda6e9259c353925571263a6a155c1'

stages:
  - stage: SonarQubeAnalysis
    displayName: Run SonarQube Analysis on QA Repo
    jobs:
      - job: SonarQubeScan
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - script: |
              mvn clean verify sonar:sonar \
                -Dsonar.projectKey=$(sonarProjectKey) \
                -Dsonar.projectName='$(sonarProjectName)' \
                -Dsonar.host.url=$(sonarHostUrl) \
                -Dsonar.token=$(sonarToken)
            displayName: Run Maven SonarQube Scan
